module cpu_pp #(
    parameter ADDR_W = 32,
    parameter DATA_W = 32,
    parameter DEPTH  = 256
)(
    input  wire clk,
    input  wire rst,
    output wire halt
);
//=============================================================================
// 1) Local parameters
//==============================================================================


//==============================================================================
// 2) Variables declaration
//==============================================================================

    // ---------------------------------------------------------
    // FETCH STAGE
    // ---------------------------------------------------------
    reg  [ADDR_W-1:0] F_PC;         // Program counter is byte-indexed (ADDR_W bits)
    wire [ADDR_W-1:0] F_PCnext;     // Next PC value after selection logic
    wire [ADDR_W-1:0] F_PCjump;     // Jump target address for J-type instructions
    wire [ADDR_W-1:0] F_PCplus4;    // Next sequential instruction
    wire [DATA_W-1:0] F_instr;      // Instruction fetched from instruction memory

    // ---------------------------------------------------------
    // DECODE STAGE
    // ---------------------------------------------------------
    reg  [ADDR_W-1:0] D_PCplus4;
    reg  [DATA_W-1:0] D_instr;
    wire [DATA_W-1:0] D_rf_out1, D_rf_out2, D_imm_ext;
    wire [25:0] D_addr;
    wire [15:0] D_imm;
    wire [5:0]  D_opcode;
    wire [4:0]  D_rs, D_rt, D_rd, D_shamt;

    // Control signals generated by control unit
    wire       D_regWrite, D_regDst, D_aluSrc, D_memWrite, D_memtoReg, D_take_branch;
    wire [2:0] D_aluControl;
    wire       D_jump, D_is_shift, D_imm_is_zext, D_signed_less;

    wire D_halt;

    // ---------------------------------------------------------
    // EXECUTE STAGE
    // ---------------------------------------------------------
    reg  [ADDR_W-1:0] E_PCplus4, E_PCbranch;
    reg  [DATA_W-1:0] E_imm_ext, E_rf_out1, E_rf_out2;
    reg  [4:0]        E_rt, E_rd, E_shamt, E_wa3;
    reg  [2:0]        E_aluControl;
    reg               E_regWrite, E_memtoReg, E_memWrite, E_aluSrc, E_regDst;
    reg               E_take_branch, E_is_shift, E_signed_less;
    wire [DATA_W-1:0] E_aluA, E_aluB, E_aluOut;
    wire              E_aluOut_is_zero;

    // ---------------------------------------------------------
    // MEMORY STAGE
    // ---------------------------------------------------------
    reg  [ADDR_W-1:0] M_PCbranch;
    reg  [DATA_W-1:0] M_aluOut, M_rf_out2;
    reg  [4:0]        M_wa3;
    reg               M_regWrite, M_memtoReg, M_memWrite, M_take_branch, M_aluOut_is_zero;
    wire [DATA_W-1:0] M_dmOut;

    // ---------------------------------------------------------
    // WRITEBACK STAGE
    // ---------------------------------------------------------
    reg  [DATA_W-1:0] W_dmOut, W_aluOut;
    reg  [4:0]        W_wa3;
    reg               W_regWrite, W_memtoReg;
    wire [DATA_W-1:0] W_rf_in;

//==============================================================================
// 3) Assignments and always blocks
//==============================================================================

    // ---------------------------------------------------------
    // FETCH STAGE
    // ---------------------------------------------------------
    // PC register
    always @(posedge clk) begin
        if (rst)
            F_PC <= {ADDR_W{1'b0}};
        else if (!halt)
            F_PC <= F_PCnext;
    end

    assign F_PCplus4 = F_PC + 4;
    assign F_PCjump   = {F_PC[ADDR_W-1:ADDR_W-4], D_addr, 2'b00};
    assign F_PCnext   =
        (D_jump)        ? F_PCjump   :
        (M_take_branch) ? M_PCbranch : F_PCplus4;

    //---------------------------------------------------------
    // DECODE STAGE
    //---------------------------------------------------------

    // D register
    always @(posedge clk) begin
        if(rst || D_jump || D_halt) begin     // Flush the decode stage on reset, jump, or halt by clearing the instruction and PC+4
                                              // incurs a one-cycle bubble to prevent incorrect branch calculations
            D_instr    <= {DATA_W{1'b0}};
            D_PCplus4  <= {ADDR_W{1'b0}};
        end else begin
            D_instr   <= F_instr;
            D_PCplus4 <= F_PCplus4;
        end
    end

    assign D_imm_ext = (D_imm_is_zext) ? {16'b0, D_imm} : {{16{D_imm[15]}}, D_imm};
    assign D_opcode = D_instr[DATA_W-1:26];
    assign D_rs     = D_instr[25:21];
    assign D_rt     = D_instr[20:16];
    assign D_rd     = D_instr[15:11];
    assign D_shamt  = D_instr[10:6];
    assign D_imm    = D_instr[15:0];
    assign D_addr   = D_instr[25:0];

    //---------------------------------------------------------
    // EXECUTE STAGE
    //---------------------------------------------------------
    // E register
    always @(posedge clk) begin
        if(rst) begin
            E_regWrite    <= 1'b0;
            E_memtoReg    <= 1'b0;
            E_memWrite    <= 1'b0;
            E_aluControl  <= 3'b000;
            E_aluSrc      <= 1'b0;
            E_regDst      <= 1'b0;
            E_PCplus4     <= {ADDR_W{1'b0}};
            E_imm_ext     <= {DATA_W{1'b0}};
            E_take_branch <= 1'b0;
            E_rt          <= {5{1'b0}};
            E_rd          <= {5{1'b0}};
            E_rf_out1     <= {DATA_W{1'b0}};
            E_rf_out2     <= {DATA_W{1'b0}};
            E_shamt       <= {5{1'b0}};
            E_is_shift    <= 1'b0;
            E_signed_less <= 1'b0;
        end else begin
            E_regWrite    <= D_regWrite;
            E_memtoReg    <= D_memtoReg;
            E_memWrite    <= D_memWrite;
            E_aluControl  <= D_aluControl;
            E_aluSrc      <= D_aluSrc;
            E_regDst      <= D_regDst;
            E_PCplus4     <= D_PCplus4;
            E_imm_ext     <= D_imm_ext;
            E_take_branch <= D_take_branch;
            E_rt          <= D_rt;
            E_rd          <= D_rd;
            E_rf_out1     <= D_rf_out1;
            E_rf_out2     <= D_rf_out2;
            E_shamt       <= D_shamt;
            E_is_shift    <= D_is_shift;
            E_signed_less <= D_signed_less;
        end
    end

    assign E_PCbranch = E_PCplus4 + E_imm_ext;
    assign E_wa3 = (E_regDst) ? E_rd : E_rt;    // Register File write Address (A3)

    // ALU operand A:
    //   - for shifts: use shamt (zero-extended)
    //   - otherwise: use rs data
    assign E_aluA = (E_is_shift) ? {27'b0, E_shamt} : E_rf_out1;

    // ALU operand B:
    //   - E_aluSrc=1 selects E_imm_ext
    //   - E_aluSrc=0 selects rt data
    assign E_aluB = (E_aluSrc) ? E_imm_ext : E_rf_out2;
    
    //---------------------------------------------------------
    // MEMORY STAGE
    //---------------------------------------------------------
    // M register
    always @(posedge clk) begin
        if(rst) begin
            M_regWrite       <= 1'b0;
            M_memtoReg       <= 1'b0;
            M_memWrite       <= 1'b0;
            M_PCbranch       <= {ADDR_W{1'b0}};
            M_take_branch    <= 1'b0;
            M_wa3            <= {5{1'b0}};
            M_rf_out2        <= {DATA_W{1'b0}};
            M_aluOut         <= {DATA_W{1'b0}};
            M_aluOut_is_zero <= 1'b0;
        end else begin
            M_regWrite       <= E_regWrite;
            M_memtoReg       <= E_memtoReg;
            M_memWrite       <= E_memWrite;
            M_PCbranch       <= E_PCbranch;
            M_take_branch    <= E_take_branch;
            M_wa3            <= E_wa3;
            M_rf_out2        <= E_rf_out2;
            M_aluOut         <= E_aluOut;
            M_aluOut_is_zero <= E_aluOut_is_zero;
        end
    end

    //---------------------------------------------------------
    // WRITEBACK STAGE
    //---------------------------------------------------------
    // WB register
    always @(posedge clk) begin
        if(rst) begin
            W_regWrite <= 1'b0;
            W_memtoReg <= 1'b0;
            W_wa3      <= {5{1'b0}};
            W_dmOut    <= {DATA_W{1'b0}};
            W_aluOut   <= {DATA_W{1'b0}};
        end else begin
            W_regWrite <= M_regWrite; 
            W_memtoReg <= M_memtoReg;
            W_wa3      <= M_wa3;
            W_dmOut    <= M_dmOut;
            W_aluOut   <= M_aluOut;
        end
    end

    assign W_rf_in = (W_memtoReg)? W_dmOut : W_aluOut;

//==============================================================================
// 4) Submodules instantiation
//==============================================================================

    //-------------------------------------------------------------------------
    // Register file
    //-------------------------------------------------------------------------

    register_file #(
        .ADDR_W (ADDR_W),
        .DATA_W (DATA_W),
        .NREGS  (NREGS)
    ) register_file (
        .clk        (clk),
        .rst        (rst),
        .we3        (W_regWrite),
        .rd1        (D_rs),         //A1
        .rd2        (D_rt),         //A2   
        .wa3        (W_wa3),        //A3
        .data_in    (W_rf_in),
        .data_out1  (D_rf_out1),
        .data_out2  (D_rf_out2)
    );

    //------------------------------------------------------------------------------
    // Instruction memory
    //------------------------------------------------------------------------------

    intr_mem #(
        .ADDR_W  (ADDR_W),
        .INSTR_W (INSTR_W),
        .DEPTH   (DEPTH)
    ) instr_mem (
        .addr_in   (F_PC),
        .instr_out (F_instr)
    );

    //------------------------------------------------------------------------------
    // Data memory
    //------------------------------------------------------------------------------
    
    data_mem #(
        .ADDR_W(ADDR_W)
    ) data_mem (
        .clk     (clk),
        .we      (M_memWrite),
        .addr    (M_aluOut[ADDR_W-1:0]),
        .data_in (M_rf_out2),           // Store data comes from rt register
        .data_out(M_dmOut)             // Load data goes to writeback mux
    );

    //------------------------------------------------------------------------------
    // Control unit
    //------------------------------------------------------------------------------

    control_unit #(
        .INSTR_W        (INSTR_W)
    ) control_unit (
        .instr          (D_instr),        // Current instruction
        .aluOut_is_zero (M_aluOut_is_zero), // ALU result is zero flag
        .signed_less    (D_signed_less),    // ALU signed less flag
        .aluControl     (D_aluControl),   // ALU operation control
        .regWrite       (D_regWrite),     // Enable register write
        .regDst         (D_regDst),       // Select destination register (rd vs rt)
        .aluSrc         (D_aluSrc),       // Select ALU source B (imm vs reg)
        .take_branch    (D_take_branch),  // Branch condition met
        .memWrite       (D_memWrite),     // Enable data memory write
        .memtoReg       (D_memtoReg),     // Select writeback source (mem vs ALU)
        .jump           (D_jump),         // Jump instruction
        .is_shift       (D_is_shift),       // Shift operation flag
        .imm_is_zext    (D_imm_is_zext),    // Zero-extend immediate flag
        .halt           (D_halt)            // Halt signal
    );

    //------------------------------------------------------------------------------
    // ALU
    //------------------------------------------------------------------------------

    alu #(
        .DATA_W(DATA_W)
    ) alu (
        .aluControl (E_aluControl),
        .in_a       (E_aluA),
        .in_b       (E_aluB),
        .out        (E_aluOut),
        .is_zero    (E_aluOut_is_zero),
        .signed_less(E_signed_less)
    );
endmodule