module pp_cpu #(
    parameter ADDR_W = 32,
    parameter DATA_W = 32,
    parameter DEPTH  = 256
)(
    input  wire clk,
    input  wire rst,
    output wire halt
);
//==============================================================================
// 2) Variables declaration
//==============================================================================

    // ---------------------------------------------------------
    // FETCH STAGE
    // ---------------------------------------------------------
    reg  [ADDR_W-1:0] F_PC;         // Program counter is byte-indexed (ADDR_W bits)
    wire [ADDR_W-1:0] F_PCnext;     // Next PC value after selection logic
    wire [ADDR_W-1:0] F_PCjump;     // Jump target address for J-type instructions
    wire [ADDR_W-1:0] F_PCplus4;    // Next sequential instruction
    wire [ADDR_W-1:0] F_mem_addr;      // instruction-side byte address
    wire [ADDR_W-1:0] F_mem_addr_word; // instruction-side word index
    wire [DATA_W-1:0] F_instr;      // Instruction fetched from instruction memory

    // ---------------------------------------------------------
    // DECODE STAGE
    // ---------------------------------------------------------
    reg  [ADDR_W-1:0] D_PCplus4, D_PCbranch;
    reg  [DATA_W-1:0] D_instr;
    wire [DATA_W-1:0] D_rf_out1, D_rf_out2, D_imm_ext, D_branchOperandA, D_branchOperandB;
    wire [DATA_W-1:0] D_rf_out1_eff, D_rf_out2_eff;
    wire [25:0] D_addr;
    wire [15:0] D_imm;
    wire [5:0]  D_opcode;
    wire [4:0]  D_rs, D_rt, D_rd, D_shamt;
    wire D_take_branch, D_take_branch_raw, D_halt, D_EN, D_CLR;
    wire D_forwardB, D_forwardA;

    // Control signals generated by control unit
    wire       D_regWrite, D_regDst, D_aluSrc, D_memWrite, D_memtoReg;
    wire [2:0] D_aluControl;
    wire       D_jump, D_is_shift, D_imm_is_zext, D_is_beq, D_is_bne, D_is_blt, D_branch;
    // ---------------------------------------------------------
    // EXECUTE STAGE
    // ---------------------------------------------------------

    reg  [DATA_W-1:0] E_imm_ext, E_rf_out1, E_rf_out2, E_intermediateA, E_intermediateB;
    reg  [4:0]        E_rt, E_rd, E_shamt, E_rs, E_wa3;
    reg  [2:0]        E_aluControl;
    reg               E_regWrite, E_memtoReg, E_memWrite, E_aluSrc, E_regDst, E_signed_less;
    reg               E_is_shift;
    wire [1:0]        E_forwardA, E_forwardB;
    wire [DATA_W-1:0] E_aluA, E_aluB, E_aluOut;
    wire              E_aluOut_is_zero, E_flush;

    // ---------------------------------------------------------
    // MEMORY STAGE
    // ---------------------------------------------------------
    reg  [DATA_W-1:0] M_aluOut, M_writeData;
    reg  [4:0]        M_wa3;
    reg               M_regWrite, M_memtoReg, M_memWrite;
    wire [ADDR_W-1:0] M_mem_addr;      // data-side byte address
    wire [ADDR_W-1:0] M_mem_addr_word; // data-side word index
    wire [DATA_W-1:0] M_dmOut;

    // ---------------------------------------------------------
    // WRITEBACK STAGE
    // ---------------------------------------------------------
    reg  [DATA_W-1:0] W_dmOut, W_aluOut;
    reg  [4:0]        W_wa3;
    reg               W_regWrite, W_memtoReg;
    wire [DATA_W-1:0] W_rf_in;

    // ---------------------------------------------------------
    // HAZARD DETECTION UNIT
    // ---------------------------------------------------------
    wire F_stall, D_stall;
    
//==============================================================================
// 3) Assignments and always blocks
//==============================================================================

    // ---------------------------------------------------------
    // FETCH STAGE
    // ---------------------------------------------------------
    // PC register
    always @(posedge clk) begin
        if (rst)
            F_PC <= {ADDR_W{1'b0}};
        else if (!D_halt && !F_stall)   // Only update PC if not stalled and not halted
            F_PC <= F_PCnext;
    end

    assign F_PCplus4 = F_PC + 4;
    assign F_mem_addr = F_PC;                                      // Instruction-side byte address comes directly from architectural PC.
    assign F_mem_addr_word = {{2{1'b0}}, F_mem_addr[ADDR_W-1:2]};  // Convert byte address to word index for instr_mem.
    assign F_PCjump   = {D_PCplus4[ADDR_W-1:ADDR_W-4], D_addr, 2'b00};
    assign F_PCnext   =
        (D_jump)        ? F_PCjump   :
        (D_take_branch) ? D_PCbranch : F_PCplus4;

    //---------------------------------------------------------
    // DECODE STAGE
    //---------------------------------------------------------

    // D register
    always @(posedge clk) begin
        if(rst || D_CLR) begin     // Flush the decode stage on reset, jump, or halt by clearing the instruction and PC+4
                                              // incurs a one-cycle bubble to prevent incorrect branch calculations
            D_instr    <= {DATA_W{1'b0}};
            D_PCplus4  <= {ADDR_W{1'b0}};
        end else if (D_EN) begin // Introduce a stall condition to prevent overwriting the decode stage registers when a hazard is detected
            D_instr   <= F_instr;
            D_PCplus4 <= F_PCplus4;
        end
    end

    // Forwarding logic for Decode stage operands (D_branchOperandA and D_branchOperandB) is implemented using the D_forwardA and D_forwardB signals generated by the hazard unit.
    assign D_branchOperandA =  D_forwardA ? M_aluOut : D_rf_out1_eff;
    assign D_branchOperandB =  D_forwardB ? M_aluOut : D_rf_out2_eff;

    // WB->Decode bypass: if WB writes the same register being read in Decode,
    // use W_rf_in directly to avoid same-cycle RF read-after-write hazards.
    assign D_rf_out1_eff = (W_regWrite && (W_wa3 != 5'd0) && (W_wa3 == D_rs)) ? W_rf_in : D_rf_out1;
    assign D_rf_out2_eff = (W_regWrite && (W_wa3 != 5'd0) && (W_wa3 == D_rt)) ? W_rf_in : D_rf_out2;
    //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    assign D_opcode = D_instr[DATA_W-1:26];
    assign D_rs     = D_instr[25:21];
    assign D_rt     = D_instr[20:16];
    assign D_rd     = D_instr[15:11];
    assign D_shamt  = D_instr[10:6];
    assign D_imm    = D_instr[15:0];
    assign D_addr   = D_instr[25:0];

    assign D_PCbranch = D_PCplus4 + (D_imm_ext << 2);  // Branch immediate is word offset; shift-left by 2 in byte-PC domain.
    assign D_imm_ext = (D_imm_is_zext) ? {16'b0, D_imm} : {{16{D_imm[15]}}, D_imm};

    assign D_branch = D_is_beq || D_is_bne || D_is_blt;

    // Early branch detection logic: if the instruction in the Decode stage is a branch instruction (BEQ, BNE, or BLT), 
    // we need to check if the branch condition is met. If so, we will flush the pipeline to prevent incorrect instructions from being executed.
    assign D_take_branch_raw = (D_is_beq && (D_branchOperandA == D_branchOperandB)) |
                               (D_is_bne && (D_branchOperandA != D_branchOperandB)) |
                               (D_is_blt && ($signed(D_branchOperandA) < $signed(D_branchOperandB)));
    // Branch must be decided only when Decode is not stalled; otherwise, it may
    // use stale operands and redirect PC incorrectly.
    assign D_take_branch = D_take_branch_raw && !D_stall;

    assign D_CLR = D_jump || D_take_branch;  // Clear the decode stage on jump or branch taken
    assign D_EN  = !D_stall;                 // Enable the decode stage if not stalled

    //---------------------------------------------------------
    // EXECUTE STAGE
    //---------------------------------------------------------
    // E register
    always @(posedge clk) begin
        if(rst || E_flush) begin
            E_regWrite    <= 1'b0;
            E_memtoReg    <= 1'b0;
            E_memWrite    <= 1'b0;
            E_aluControl  <= 3'b000;
            E_aluSrc      <= 1'b0;
            E_regDst      <= 1'b0;
            E_imm_ext     <= {DATA_W{1'b0}};
            E_rt          <= {5{1'b0}};
            E_rd          <= {5{1'b0}};
            E_rf_out1     <= {DATA_W{1'b0}};
            E_rf_out2     <= {DATA_W{1'b0}};
            E_shamt       <= {5{1'b0}};
            E_is_shift    <= 1'b0;
        end else begin
            E_regWrite    <= D_regWrite;
            E_memtoReg    <= D_memtoReg;
            E_memWrite    <= D_memWrite;
            E_aluControl  <= D_aluControl;
            E_aluSrc      <= D_aluSrc;
            E_regDst      <= D_regDst;
            E_imm_ext     <= D_imm_ext;
            E_rs          <= D_rs;
            E_rt          <= D_rt;
            E_rd          <= D_rd;
            E_rf_out1     <= D_rf_out1_eff;
            E_rf_out2     <= D_rf_out2_eff;
            E_shamt       <= D_shamt;
            E_is_shift    <= D_is_shift;
        end
    end

    // Forwarding logic for Execute stage operands (E_aluA and E_aluB) is implemented using the E_forwardA and E_forwardB signals generated by the hazard unit.
     always @* begin
        case(E_forwardA)
            2'b01  : E_intermediateA = W_rf_in;         // Forward from Writeback stage (data just written back to register file)
            2'b10  : E_intermediateA = M_aluOut;        // Forward from Memory stage (data available at the end of Memory stage, can be used in Execute stage of next instruction)
            default: E_intermediateA = E_rf_out1;       // No hazard, use data read from register file in Decode stage
        endcase

        case(E_forwardB)
            2'b01  : E_intermediateB = W_rf_in;         // Forward from Writeback stage (data just written back to register file)
            2'b10  : E_intermediateB = M_aluOut;        // Forward from Memory stage (data available at the end of Memory stage, can be used in Execute stage of next instruction)
            default: E_intermediateB = E_rf_out2;       // No hazard, use data read from register file in Decode stage
        endcase
    end
    //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    assign E_wa3 = (E_regDst) ? E_rd : E_rt;    // Register File write Address (A3)

    // ALU operand A:
    //   - for shifts: use shamt (zero-extended)
    //   - otherwise: use rs data
    assign E_aluA = (E_is_shift) ? {27'b0, E_shamt} : E_intermediateA;

    // ALU operand B:
    //   - E_aluSrc=1 selects E_imm_ext
    //   - E_aluSrc=0 selects rt data
    assign E_aluB = (E_aluSrc) ? E_imm_ext : E_intermediateB;
    //---------------------------------------------------------
    // MEMORY STAGE
    //---------------------------------------------------------
    // M register
    always @(posedge clk) begin
        if(rst) begin
            M_regWrite       <= 1'b0;
            M_memtoReg       <= 1'b0;
            M_memWrite       <= 1'b0;
            M_wa3            <= {5{1'b0}};
            M_writeData      <= {DATA_W{1'b0}};
            M_aluOut         <= {DATA_W{1'b0}};
        end else begin
            M_regWrite       <= E_regWrite;
            M_memtoReg       <= E_memtoReg;
            M_memWrite       <= E_memWrite;
            M_wa3            <= E_wa3;
            M_writeData      <= E_intermediateB;   // Store data comes from rt register (after forwarding logic)
            M_aluOut         <= E_aluOut;
        end
    end

    assign M_mem_addr = M_aluOut;  // ALU generates data-side byte address.
    assign M_mem_addr_word = {{2{1'b0}}, M_mem_addr[ADDR_W-1:2]};  // Convert byte address to word index for data_mem.

    //---------------------------------------------------------
    // WRITEBACK STAGE
    //---------------------------------------------------------
    // WB register
    always @(posedge clk) begin
        if(rst) begin
            W_regWrite <= 1'b0;
            W_memtoReg <= 1'b0;
            W_wa3      <= {5{1'b0}};
            W_dmOut    <= {DATA_W{1'b0}};
            W_aluOut   <= {DATA_W{1'b0}};
        end else begin
            W_regWrite <= M_regWrite; 
            W_memtoReg <= M_memtoReg;
            W_wa3      <= M_wa3;
            W_dmOut    <= M_dmOut;
            W_aluOut   <= M_aluOut;
        end
    end

    assign W_rf_in = (W_memtoReg)? W_dmOut : W_aluOut;
//==============================================================================
// 4) Submodules instantiation
//==============================================================================

    //-------------------------------------------------------------------------
    // Register file
    //-------------------------------------------------------------------------

    register_file #(
        .DATA_W (DATA_W)
    ) register_file (
        .clk        (clk),
        .rst        (rst),
        .we3        (W_regWrite),
        .rd1        (D_rs),         //A1
        .rd2        (D_rt),         //A2   
        .wa3        (W_wa3),        //A3
        .data_in    (W_rf_in),
        .data_out1  (D_rf_out1),
        .data_out2  (D_rf_out2)
    );

    //------------------------------------------------------------------------------
    // Instruction memory
    //------------------------------------------------------------------------------

    instr_mem #(
        .ADDR_W  (ADDR_W),
        .INSTR_W (DATA_W),
        .DEPTH   (DEPTH)
    ) instr_mem (
        .addr_in   (F_mem_addr_word),
        .instr_out (F_instr)
    );

    //------------------------------------------------------------------------------
    // Data memory
    //------------------------------------------------------------------------------
    
    data_mem #(
        .ADDR_W(ADDR_W)
    ) data_mem (
        .clk     (clk),
        .we      (M_memWrite),
        .addr    (M_mem_addr_word),
        .data_in (M_writeData),           // Store data comes from rt register
        .data_out(M_dmOut)             // Load data goes to writeback mux
    );

    //------------------------------------------------------------------------------
    // Control unit
    //------------------------------------------------------------------------------

    control_unit #(
        .INSTR_W        (DATA_W)
    ) control_unit (
        .instr          (D_instr),        // Current instruction
        .aluControl     (D_aluControl),   // ALU operation control
        .regWrite       (D_regWrite),     // Enable register write
        .regDst         (D_regDst),       // Select destination register (rd vs rt)
        .aluSrc         (D_aluSrc),       // Select ALU source B (imm vs reg)
        .memWrite       (D_memWrite),     // Enable data memory write
        .memtoReg       (D_memtoReg),     // Select writeback source (mem vs ALU)
        .jump           (D_jump),         // Jump instruction
        .is_shift       (D_is_shift),     // Shift operation flag
        .is_beq         (D_is_beq),       // BEQ instruction flag
        .is_bne         (D_is_bne),       // BNE instruction flag
        .is_blt         (D_is_blt),       // BLT instruction flag
        .imm_is_zext    (D_imm_is_zext),  // Zero-extend immediate flag
        .halt           (D_halt)          // Halt signal
    );

    //------------------------------------------------------------------------------
    // ALU
    //------------------------------------------------------------------------------

    alu #(
        .DATA_W(DATA_W)
    ) alu (
        .aluControl (E_aluControl),
        .in_a       (E_aluA),
        .in_b       (E_aluB),
        .out        (E_aluOut),
        .is_zero    (E_aluOut_is_zero),
        .signed_less(E_signed_less)
    );

    //------------------------------------------------------------------------------
    // Hazard unit
    //------------------------------------------------------------------------------

    hazard_unit hazard_unit(
        .D_branch   (D_branch),
        .E_regWrite (E_regWrite),
        .E_memtoReg (E_memtoReg),
        .M_regWrite (M_regWrite),
        .W_regWrite (W_regWrite),
        .M_memtoReg (M_memtoReg),
        .D_rs       (D_rs),
        .D_rt       (D_rt),
        .E_rs       (E_rs),
        .E_rt       (E_rt),
        .M_wa3      (M_wa3),
        .W_wa3      (W_wa3),
        .E_wa3      (E_wa3),
        .forwardAE  (E_forwardA),
        .forwardAD  (D_forwardA),
        .forwardBE  (E_forwardB),
        .forwardBD  (D_forwardB),
        .F_stall    (F_stall),
        .D_stall    (D_stall),
        .E_flush    (E_flush)
    );

endmodule