#!/usr/bin/env bash
#==============================================================================
# setup.sh - Automatic configuration setup for synthesis environment
#
# This script auto-detects tools and PDK paths, creating a .env file
# Usage: ./setup.sh [--force]
#==============================================================================

set -e

# ANSI color codes
BLUE='\033[1;34m'
GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

FORCE_SETUP=0
if [[ "$1" == "--force" ]]; then
    FORCE_SETUP=1
fi

# Find project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$(cd "$SCRIPT_DIR" && cd ..)" && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

echo -e "${BLUE}========== Synthesis Environment Setup ==========${NC}"
echo

# Check if .env already exists
if [[ -f "$ENV_FILE" && $FORCE_SETUP -eq 0 ]]; then
    echo -e "${GREEN}✓${NC} .env file already exists at $ENV_FILE"
    echo -e "${YELLOW}ℹ${NC} To reconfigure, run: $0 --force"
    exit 0
fi

if [[ -f "$ENV_FILE" && $FORCE_SETUP -eq 1 ]]; then
    echo -e "${YELLOW}⚠${NC} Reconfiguring .env (backup at ${ENV_FILE}.bak)"
    mv "$ENV_FILE" "$ENV_FILE.bak"
fi

# ============================================================================
# Auto-detect tools
# ============================================================================

echo "1. Detecting synthesis tools..."

# Detect Yosys
if command -v yosys &> /dev/null; then
    YOSYS_PATH=$(command -v yosys)
    YOSYS_VERSION=$(yosys --version | head -n1)
    echo -e "${GREEN}✓${NC} Yosys found: $YOSYS_VERSION"
else
    echo -e "${RED}✗${NC} Yosys not found in PATH"
    echo "  Install: https://github.com/YosysHQ/yosys"
    exit 1
fi

# Detect Netlistsvg
if command -v netlistsvg &> /dev/null; then
    NETLISTSVG_PATH=$(command -v netlistsvg)
    echo -e "${GREEN}✓${NC} Netlistsvg found at $NETLISTSVG_PATH"
    HAS_NETLISTSVG=1
else
    echo -e "${YELLOW}⚠${NC} Netlistsvg not found (optional - diagrams will be skipped)"
    HAS_NETLISTSVG=0
fi
echo

# ============================================================================
# Manual Sky130 PDK Configuration
# ============================================================================

echo "2. Configuring Sky130 PDK..."

FOUND_SKY130=0
SKY130_PATH=""

echo "Please provide the path to your Sky130 library file:"
echo "Example: /home/username/pdk/volare/sky130/.../sky130_fd_sc_hd__tt_100C_1v80.lib"
echo
read -p "Enter Sky130 library path (or press Enter to skip): " SKY130_INPUT

if [[ -n "$SKY130_INPUT" ]]; then
    if [[ -f "$SKY130_INPUT" ]]; then
        SKY130_PATH="$SKY130_INPUT"
        FOUND_SKY130=1
        echo -e "${GREEN}✓${NC} Sky130 library path set successfully!"
    else
        echo -e "${RED}✗${NC} File not found at: $SKY130_INPUT"
        echo "  Continuing without Sky130 (generic synthesis only)"
    fi
else
    echo -e "${YELLOW}ℹ${NC} Sky130 PDK skipped"
    echo "  Continuing with generic synthesis only"
fi
echo

# ============================================================================
# Create .env file
# ============================================================================

echo "3. Creating .env configuration file..."

cat > "$ENV_FILE" << EOF
# RTL Hardware Development Project Configuration
# Generated by setup.sh on $(date)
# 
# Edit this file to customize your local environment
# This file should NOT be committed to git (.gitignore)

# Synthesis Tools
YOSYS_BIN=$(command -v yosys)
NETLISTSVG_BIN=$(command -v netlistsvg 2>/dev/null || echo "netlistsvg")

# Sky130 PDK Library Path
EOF

if [[ -n "$SKY130_PATH" ]]; then
    echo "SKY130_LIB_PATH=$SKY130_PATH" >> "$ENV_FILE"
else
    cat >> "$ENV_FILE" << EOF
# Sky130 library not found
# Set this to enable technology-specific synthesis:
# SKY130_LIB_PATH=/path/to/sky130_fd_sc_hd__tt_100C_1v80.lib
SKY130_LIB_PATH=
EOF
fi

cat >> "$ENV_FILE" << EOF

# Optional: Additional library variants
# SKY130_LIB_PATH_FAST=/path/to/sky130_fd_sc_hd__ff_n40C_1v95.lib
# SKY130_LIB_PATH_SLOW=/path/to/sky130_fd_sc_hd__ss_125C_1v40.lib
EOF

echo -e "${GREEN}✓${NC} Configuration saved to: $ENV_FILE"
echo

# ============================================================================
# Verification
# ============================================================================

echo "4. Verifying configuration..."

# Source the new config
source "$PROJECT_ROOT/synth/config.sh"

# Run health check
if bash "$PROJECT_ROOT/synth/check_env.sh" &>/dev/null; then
    echo -e "${GREEN}✓${NC} Configuration verified successfully!"
else
    echo -e "${YELLOW}⚠${NC} Configuration verification had warnings"
fi
echo

# ============================================================================
# Summary
# ============================================================================

echo "=========================================="
echo -e "${GREEN}Setup Complete!${NC}"
echo "=========================================="
echo
echo "Configuration file created: $ENV_FILE"
echo
if [[ $FOUND_SKY130 -eq 1 ]]; then
    echo "Ready to use:"
    echo "  cd synth"
    echo "  ./generic_synth.sh <module>"
    echo "  ./specific_synth.sh <module>"
else
    echo "Sky130 PDK not configured."
    echo "Generic synthesis available:"
    echo "  cd synth"
    echo "  ./generic_synth.sh <module>"
    echo
    echo "To enable technology-specific synthesis:"
    echo "  1. Install Sky130 PDK"
    echo "  2. Run: $0 --force"
fi
echo

exit 0
