//==============================================================================
// sc_cpu.sv
//
// Module: sc_cpu
// Type  : MIPS-like single-cycle CPU top (PC-indexed instruction memory)
//
// PURPOSE
//   - Connects instruction memory, control unit, register file, ALU, and data memory
//   - Implements PC update (pc_next selection) and architectural state updates
//   - Exposes 'halted' when Control Unit detects HALT instruction
//
// ASSUMPTIONS / CONTRACT (IMPORTANT)
//   - PC is word-indexed: increments by 1 per instruction (pc_plus1 = pc + 1)
//   - Branch target uses pc_plus1 + imm_ext[ADDR_W-1:0] (low bits of immediate)
//   - Jump target uses instr[ADDR_W-1:0] (low bits of instruction)
//   - Memory addressing uses word index (addr = ALU_out[ADDR_W-1:0])
//   - Halt behavior:
//       * control_unit asserts 'halt' to stop PC updates
//
// NOTES / DESIGN CHOICES
//   - Data memory is single-ported and uses separate data buses:
//       * 'data_in' receives store data from RF_data_out2
//       * 'data_out' is exposed internally as 'DM_out' for loads/writeback
//   - Shift instructions:
//       * ALU input A uses shamt (zero-extended) when instruction is shift
//       * ALU input B is selected by ALUSrc (imm_ext vs RF_data_out2)
//
// DEBUG OBSERVABILITY
//   - Internal signals are named to be waveform-friendly:
//       pc, pc_next, instr, opcode, rs/rt/rd, imm_ext
//       regWrite, memWrite, memtoReg, jump, take_branch
//       wa3, RF_wdata, ALU_out, ALU_is_zero, DM_out
//==============================================================================

module sc_cpu #(
    parameter int ADDR_W = 8,
    parameter int DATA_W = 32,
    parameter int DEPTH  = 256
)(
    input  wire clk,
    input  wire rst,
    output wire halt
);
    //==============================================================================
    // 1) Local parameters
    //==============================================================================

    localparam INSTR_W = 32;

    //==============================================================================
    // 2) Architectural state (PC) + halt interface
    //==============================================================================
    // Program counter is word-indexed (ADDR_W bits)
    reg  [ADDR_W-1:0] pc;

    // PC update policy:
    //   - reset forces PC=0
    //   - when halt is asserted, PC stops updating (freezes at current value)
    always @(posedge clk) begin
        if (rst)
            pc <= {ADDR_W{1'b0}};
        else if (!halt)
            pc <= pc_next;
    end

    //==============================================================================
    // 3) Instruction fields + immediate extension
    //==============================================================================
    wire [INSTR_W-1:0] instr;  // Current instruction fetched from memory

    // Decode fields (MIPS-like format)
    wire [5:0] opcode = instr[DATA_W-1:26];  // Operation code
    wire [4:0] rs     = instr[25:21];        // Source register 1
    wire [4:0] rt     = instr[20:16];        // Source register 2 / Destination for some ops
    wire [4:0] rd     = instr[15:11];        // Destination register
    wire [4:0] shamt  = instr[10:6];         // Shift amount for shift operations
    wire [5:0] funct  = instr[5:0];          // Function code for R-type instructions
    wire [15:0] imm   = instr[15:0];         // Immediate value

    // Sign-extended or zero-extended immediate based on instruction type
    wire [DATA_W-1:0] imm_ext =
        imm_is_zext ? {16'b0, imm} : {{16{imm[15]}}, imm};

    //==============================================================================
    // 4) Instruction memory
    //==============================================================================

    instr_mem # (
        .ADDR_W (ADDR_W),
        .INSTR_W(INSTR_W),
        .DEPTH  (DEPTH)
    ) instr_mem (
        .addr_in   (pc),         // Address input: current PC
        .instr_out (instr)       // Instruction output
    );

    //==============================================================================
    // 5) Control unit
    //==============================================================================

    // Control signals generated by control unit based on opcode and function
    wire       regWrite, regDst, ALUSrc;
    wire [2:0] ALU_control;
    wire       memWrite, memtoReg, jump, is_shift, imm_is_zext;

    control_unit #(
        .INSTR_W        (INSTR_W)
    )control_unit (
        .instr          (instr),           // Current instruction
        .aluControl     (ALU_control),     // ALU operation control
        .regWrite       (regWrite),        // Enable register write
        .regDst         (regDst),          // Select destination register (rd vs rt)
        .aluSrc         (ALUSrc),         // Select ALU source B (imm vs reg)
        .memWrite       (memWrite),        // Enable data memory write
        .memtoReg       (memtoReg),        // Select writeback source (mem vs ALU)
        .jump           (jump),            // Jump instruction
        .is_shift       (is_shift),        // Shift operation flag
        .is_beq         (is_beq),          // BEQ instruction flag
        .is_bne         (is_bne),          // BNE instruction flag
        .is_blt         (is_blt),          // BLT instruction flag
        .imm_is_zext    (imm_is_zext),     // Zero-extend immediate flag
        .halt           (halt)             // Halt signal
    );
    //==============================================================================
    // 6) Register file (read + writeback selection)
    //==============================================================================

    wire [4:0] wa3 = (regDst) ? rd : rt;

    wire [DATA_W-1:0] RF_data_out1;     // Data from rs register
    wire [DATA_W-1:0] RF_data_out2;     // Data from rt register
    wire [DATA_W-1:0] RF_wdata;

    register_file # (
        .DATA_W     (DATA_W)
    ) register_file (
        .clk        (clk),
        .rst        (rst),
        .we3        (regWrite),
        .rd1        (rs),           //A1
        .rd2        (rt),           //A2   
        .wa3        (wa3),          //A3
        .data_in    (RF_wdata),
        .data_out1  (RF_data_out1),
        .data_out2  (RF_data_out2)
    );
    // Writeback:
    //   - memtoReg=1 selects DM_out (load)
    //   - memtoReg=0 selects ALU_out
    assign RF_wdata = (memtoReg)? DM_out : ALU_out;

    //==============================================================================
    // 7) ALU operand selection + ALU execution
    //==============================================================================

    // ALU operand A:
    //   - for shifts: use shamt (zero-extended)
    //   - otherwise: use rs data
    wire [DATA_W-1:0] ALU_a =
        (is_shift) ? {27'b0, shamt} : RF_data_out1;

    // ALU operand B:
    //   - ALUSrc=1 selects imm_ext
    //   - ALUSrc=0 selects rt data
    wire [DATA_W-1:0] ALU_b =
        (ALUSrc) ? imm_ext : RF_data_out2;

    wire [DATA_W-1:0] ALU_out;
    wire              ALU_is_zero;
    wire              ALU_signed_less;

    alu ALU (
        .aluControl  (ALU_control),
        .in_a        (ALU_a),
        .in_b        (ALU_b),
        .out         (ALU_out),
        .is_zero     (ALU_is_zero),
        .signed_less (ALU_signed_less)
    );

    //==============================================================================
    // 8) Data memory interface
    //==============================================================================
    wire [DATA_W-1:0] DM_out;

    data_mem #(
        .ADDR_W(ADDR_W)
    ) data_mem (
        .clk     (clk),
        .we      (memWrite),
        .addr    (ALU_out[ADDR_W-1:0]),
        .data_in (RF_data_out2),           // Store data comes from rt register
        .data_out(DM_out)                  // Load data goes to writeback mux
    );

    //============================================================================================
    // 9) Branch handling: determine if we should take the branch based on opcode and ALU outputs
    //============================================================================================
    //   - is_zero comes from ALU compare (typically subtraction result == 0)
    //   - For BEQ: take_branch when ALU_is_zero==1
    //   - For BNE: take_branch when ALU_is_zero==0
    //   - For BLT: take_branch when ALU_signed_less==1
    wire take_branch = (is_beq && ALU_is_zero ) |
                       (is_bne && ~ALU_is_zero) |
                       (is_blt && ALU_signed_less);
    //==============================================================================
    // 10) PC next logic (pc_plus1 / jump selection)
    //==============================================================================

    // PC + 1 (sequential next instruction)
    wire [ADDR_W-1:0] pc_plus1  = pc + 1;

    // Branch target: pc_plus1 + sign-extended immediate (low ADDR_W bits)
    wire [ADDR_W-1:0] pc_branch = pc_plus1 + imm_ext[ADDR_W-1:0];

    // Jump target: low ADDR_W bits of the instruction word
    wire [ADDR_W-1:0] pc_jump   = instr[ADDR_W-1:0];

    // Next PC selection with priority:
    //   1) Jump if jump=1
    //   2) Branch if take_branch=1
    //   3) Sequential otherwise
    wire [ADDR_W-1:0] pc_next   =
        (jump)        ? pc_jump   :
        (take_branch) ? pc_branch : pc_plus1;

endmodule